Add validation filter.
mindedtech/prisma-directus pull request #4
Opened 2024-06-17 07:48 UTC by hamzace

**Changes**

- Added a validation filter when creating a data model, helping us to make the difference between `Field validation` and `Item permissions` in `Directus`.
- Added a `npm pack` script in `package.json`

2024-06-17 08:01 UTC, elierotenberg commented
nit: shouldn't commit prefix be `feat`?

2024-06-26 10:14 UTC, elierotenberg requested changes

2024-06-26 10:14 UTC, elierotenberg commented on packages/generator/package.json
> +    "build": "npm run build:clean && npm run build:ts && npm run build:prisma && npm run build:pack",
https://github.com/mindedtech/mosaic/blob/main/.devcontainer/docker-compose.devcontainer.yml#L26-L36

2024-06-28 14:22 UTC, hamzace commented on packages/generator/package.json
> +    "build": "npm run build:clean && npm run build:ts && npm run build:prisma && npm run build:pack",
done

2024-08-08 09:46 UTC, closed without merging